---
title: "eBay Assignment Marketing Analytics"
author: "Debarati Mazumdar, Maura Oray"
date: "10/21/2018"
output:
  word_document: default
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(ggplot2)
library(tidyverse)
library(randomizeR)
#The required libraries for the case analysis 
```


```{r pressure, echo=FALSE}
ebay<- read.csv("~/Desktop/Fall 2018/Marketing Analytics /CASE 1/eBayData.csv")
summary(ebay)
str(ebay)
dim(ebay)
# We see that the dataset has 5 variables wih 23,730 rows.
# Revenue is  with a minimum of $367 and maximum of $2,601,390 with a median of $53,919
# Date is a factor,(dma , isTreatmentPeriod, isTreatmentGroup) are integers,
# Revenue is numerical. 
```

```{r}
# a. Convert the Date Column 
ebay$rDate <- as.Date(ebay$date, format="%m/%d/%y") 
head(ebay)
# the date column is changed into date type as the 6th new column 
```

```{r}
# Convert the type into factors for statistical analysis for column  3 and 4 as for regression the categorical variables have to be factor variables.
ebay[3:4] <- lapply(ebay[3:4], factor)
is.factor(ebay$isTreatmentGroup) # check if the variable is factor
is.factor(ebay$isTreatmentPeriod) # check if the variable is factor
#b) Treatment Period Date start date 
#ebay = subset(ebay[order(ebay$rDate), ],isTreatmentPeriod == "1") 
#head(ebay)
#Treatment start date is 5/22/2012 for the analysis

```

```{r}
a = table(ebay$isTreatmentGroup, ebay$isTreatmentPeriod)
t = as.data.frame(a)
names(t)[1] = 'Treatment Group' #header for first column
names(t)[2] = 'Treatment Period' #header for second column
t
prop = table(ebay$isTreatmentGroup, ebay$isTreatmentPeriod)
prop.table(prop)
prop

# so when we see the table format for the taregt population we can say that, 14% of the population is in the
# control group - pre-treatment period, 17% is in the control group and treatment period 
# 30% of the population is the treatment group for pre treatment period and 37% population is in the treatment # group for the treatment period. Thus, we can see that there is a data disparity in the division of groups   # for this study
```

```{r}
#c. Regression
#Control group (0), Treatment (1). Treatment shown ads BEFORE treatment period and NOT after (0). Control group shown ads before and after.
# Hypothesis: Revenue will decrease from the treatment group after the treatment period ends. We hypothesize that removing ads will not lead to a decrease in revenue
#Combinations: 0/0 (control, before) 0/1 (control, after)
# 1/0 (treatment, before) 1/1 (treatment, after)
ebay1<- ebay %>%
filter(isTreatmentGroup == 1) 
ebay_log <- lm(log(revenue) ~ isTreatmentPeriod, data = ebay1)
summary(ebay_log)
coef(summary(ebay_log))

# So for Treatment group which is the group which is not shown ads during the treatment period. 
# The Intercept for the group during the period when ads are shown is 10.94 and for the period when ads are
# not shown is ( 10.94 - .03) = 10.91 whcih is a very small insignificant difference.
# Thus, how we read this is for every one ad shown before the treatment period there is $10.94 increase in
# revenue keeping all the other factors constant.
# The intercept 10.94 is true at 99% confidence , and 10.91 at a confidence of 90%
# p value (< 0.05) , thus we can say that we should reject the NULL, and conclude that there is significant decrease in revenue once the ads are not shown to the group
```

```{r}
#Pre treatment regression and randomization test 

# check randomization ?????

ebay2<- ebay %>%
 filter(isTreatmentPeriod == 0)
ebay_pre = lm(log(revenue) ~ isTreatmentGroup , data = ebay2)
summary(ebay_pre)
#anova( ebay_pre, ebay_log_p)
```

```{r}
# e. post treatment data to check the effectiveness of ads with dma
ebay$dma <- as.numeric(ebay$dma)
ebay_dma = lm(log(revenue) ~  dma , data = ebay) # to discuss 
summary(ebay_dma)

ebay_dma1 = lm(log(revenue) ~ isTreatmentGroup  , data = ebay)
summary(ebay_dma1)

anova( ebay_dma , ebay_dma1)

# For the analysis on revenue with Treatment group and dma, we see that intercept for treatment group 0 is 
# 21.1 and for treatment group 1 is ( 21.1 - 0.013) = 21.08 which is almost the same. However there is no #significant difference when it come to studying the difference with log(dma). 
# Both treatment group 0 and 1 behave the same way. 
# ?????????
```

```{r}
# f) Log is taken for revenue as it reduced the skewness in the variables and the results. If we observe the min  is $367 and max value of revenue is $ 2601390. Thus we see a huge band and chances of data being skewed is likely. 
# Alos if we take the regression with simple revenue the intercept value is very large and the p value is very large . This tends the analysis to be incorrect.

# g) Effectiveness of Advertising - conclusion  


```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
